apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nebula-stats-exporter
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nebula-stats-exporter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nebula-stats-exporter
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nebula-stats-exporter
subjects:
  - kind: ServiceAccount
    name: nebula-stats-exporter
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-stats-exporter
  namespace: default
  labels:
    k8s-app: nebula-stats-exporter
spec:
  selector:
    matchLabels:
      k8s-app: nebula-stats-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: nebula-stats-exporter
    spec:
      serviceAccountName: nebula-stats-exporter
      containers:
        - name: exporter
          image: vesoft/nebula-stats-exporter:v0.0.2
          imagePullPolicy: Always
          args:
            ["--listen-address=0.0.0.0:9100", "--namespace=default", "--max-request=40"]
          ports:
            - containerPort: 9100